---
- name: Configure subnet on all hosts
  hosts: all

  become: true

  vars_files:
    - vars_files/subnet_variables.yml

  tasks:
    - name: Create a new subnet and assign IP's on Debian OS
      lineinfile:
        dest: /etc/netplan/50-cloud-init.yaml
        insertafter: "^    ethernets:"
        state: present
        line: "        {{ interface_name }}: { addresses: [{{ interface_ip }}/{{ subnet_prefix }}], dhcp4: no }"
      notify:
        - Netplan Apply
      when: ansible_os_family == "Debian"

    - name: Create a new subnet and assign IP's on RedHat OS
      copy:
        content: |
          BOOTPROTO=static
          IPADDR={{ interface_ip }}
          PREFIX={{ subnet_prefix }}
          NETMASK={{ interface_mask }}
          DEVICE={{ interface_name }}
          ONBOOT=yes
        dest: "/etc/sysconfig/network-scripts/ifcfg-{{ interface_name }}"
        remote_src: true
      notify:
        - Restart Network Manager
      when: ansible_os_family == "RedHat"

  handlers:
    - name: Restart Network Manager
      service:
        name: NetworkManager
        state: restarted

    - name: Netplan Apply
      shell: "netplan apply"
