- name: Install resolvconf package on Debian OS
  package:
    name: resolvconf
    state: present
  when: ansible_os_family == 'Debian'

- name: Replace resolconf file
  copy:
    src: ../files/resolv.conf
    dest: "{{ item.dest }}"
    group: root
    owner: root
    mode: 0644
  with_items:
    - { dest: /etc/resolvconf/resolv.conf.d/head }
    - { dest: /etc/resolv.conf }
  when: ansible_os_family == 'Debian'
  notify: Restart resolvconf service

- name: Run resolvconf commands to apply configuration
  command: resolvconf -u
  when: ansible_os_family == 'Debian'

- name: Configuration for permanent resolvconf settings on RedHat OS
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: PEERDNS=no
  when: ansible_os_family == 'RedHat'

- name: Replace resolvconf file on RedHat OS
  copy:
    src: ../files/resolv.conf
    dest: /etc/resolv.conf
    group: root
    owner: root
    mode: 0644
  when: ansible_os_family == 'RedHat'
