- name: Configure services on firewall zones
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - http
    - https
    - dns

- name: Configure masquerade
  firewalld:
    zone: public
    masquerade: true
    permanent: true
    state: enabled
  notify: Reload firewalld to enable configuration

- name: Enable ipv4 forward
  command: echo -e "\nnet.ipv4.ip_forward=1" >> /etc/sysctl.conf
